### ISSUE TITLE
Leverage BUILD_LOCALLY to avoid local make error

### ISSUE THREAD

**Issue by itdove** [IBM/go-repo-template#23]
- [ ] codecov
- [ ] image upload

When we build locally, I think we don't want to upload the coverage.cov and so an extra test is needed at https://github.com/IBM/go-repo-template/blob/master/common/scripts/codecov.sh

```
BUILD_LOCALLY=${1:?0}
shift

...

# Upload to codecov.io in post submit only for visualization
if [ "$BUILD_LOCALLY" == 0 ]; then
  bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}" -f "${REPORT_PATH}/coverage.cov"
fi
```

and in the makefile:

```
############################################################
# coverage section
############################################################

coverage:
	@common/scripts/codecov.sh ${BUILD_LOCALLY}
```

**Comment by kuanf** [comment]
@morvencao @gyliu513 shall we (@itdove  ;) ) go ahead and submit pr?

Waiting for a confirmation according to the CONTRIBUTION GUIDE.  :)

**Comment by gyliu513** [comment]
@kuanf @itdove +1 for this, can you help propose a PR?

**Comment by itdove** [comment]
https://github.com/IBM/go-repo-template/pull/34
