### ISSUE TITLE
Check failed in README.md on the table of contents

### ISSUE THREAD

**Issue by itdove** [IBM/go-repo-template#25]
make check
./README.md:13: MD007 Unordered list indentation
./README.md:16: MD007 Unordered list indentation
./README.md:21: MD007 Unordered list indentation

This is automatically generated.

```
- [multicloud-operators-subscription-release](#multicloud-operators-subscription-release)
  - [What is the multicloud-operators-subscription-release](#what-is-the-multicloud-operators-subscription-release)
  - [Community, discussion, contribution, and support](#community-discussion-contribution-and-support)
  - [Getting Started](#getting-started)
    - [Prerequisites](#prerequisites)
    - [Deployment](#deployment)
    - [Trouble shooting](#trouble-shooting)
```

How we can fix it?

**Comment by kuanf** [comment]
indent 4, rather than 2.  will fix this check.

but since doctoc is generating this in so called "github.com" mode, and gives indent 2, I'm wondering what is the right format here...

**Comment by morvencao** [comment]
Let's keep the default indention to be `4`
/close
