### ISSUE TITLE
Create a make target to install all tools

### ISSUE THREAD

**Issue by itdove** [IBM/go-repo-template#28]
The template required to install a number of tools (hadolint, shellcheck, yamllint, helm, golangci-lint, autopep8, mdl, awesome_bot, sass-lint, tslint, prototool, goimports).

It seems that the version as its importance because it generates different results depending on the used version. The Prow use given version and the developers probably installed other versions as the configuration for these tools in the template is seens to be linked to a specific version. (ie: #24 , #26 ... )

So, it would be useful to have a make target in the Makefile.common.mk which install these tools with the required version. It will be up to the developers to install the recommended version using that target or to install the ones they wanted.

The target must install a tool only if not yet installed and have flag to overwrite all already installed tools with the required version.

**Comment by morvencao** [comment]
@itdove Thanks for pointing this out. Actually we have plan to make all the build process with container, so that we don't need to install so many tools in out local dev machine, and also erase the env cause for plenty of build issues.

**Comment by itdove** [comment]
That's great, I already discussed that with Kuan few days ago.
