### ISSUE TITLE
Why not configure docker usr/pwd in travis

### ISSUE THREAD

**Issue by gyliu513** [IBM/go-repo-template#51]
Seems we are configuring it in makefile at https://github.com/IBM/go-repo-template/blob/master/Makefile#L135-L136

/cc @morvencao

**Comment by morvencao** [comment]
My intention is that we can also run `make config-docker` locally for dev/test purpose. If we put that in `travis.yml`, then we can't do that.

**Comment by gyliu513** [comment]
Make sense, can you help add some comments to tell each repo owners that they can configure the usr/pwd in travis.yml for their project?

**Comment by morvencao** [comment]
sure.

**Comment by morvencao** [comment]
Closing this as we have switched to build multi-arch image with qemu in one platform, see: https://github.com/IBM/go-repo-template/pull/53

To make Travis to be another option, we keep the travis code in another branch: `br_use_travis_to_build_multi-arch_image`: https://github.com/IBM/go-repo-template/tree/br_use_travis_to_build_multi-arch_image

/close
