### ISSUE TITLE
enhance the multi-arch image build

### ISSUE THREAD

**Issue by morvencao** [IBM/go-repo-template#63]
Multi-arch image build prow job depends on image build on each platform, after the image for each platform pushed to docker registry before the multi-arch image build prow job can be started.

But looks like the prow doesn't provide dependency support for prow jobs, I have logged a feature request for this: https://github.com/kubernetes/test-infra/issues/16798

Currently, we have to check image for each platform is ready or not by script in job content, see: https://github.com/IBM/go-repo-template/blob/master/common/scripts/multiarch_image.sh
After all images are ready, the multi-arch image build prow job can be run to finally make the multi-arch image manifest.

/kind enhancement

**Comment by madhurtrilio** [comment]
Had a similar problem. Achieved this  by a pre-script within the job script, which waits for the success of dependent job and then starts execution

**Comment by madhurnawandar** [comment]
Had a similar problem. Achieved this by a pre-script within the job script, which waits for the success of dependent job and then starts execution

**Comment by madhurtrilio** [comment]
Had a similar problem. Achieved this by a pre-script within the job script, which waits for the success of dependent job and then starts execution

**Comment by morvencao** [comment]
This was fixed in https://github.com/IBM/go-repo-template/pull/86
@madhurtrilio Please follow that patch to fix the job dependency issue.
